version: "3.4"
services:
  main:
    image: prom/alertmanager
    ports: 
      - 9093:9093
    networks:
      - monitor
    command: --config.file=/run/secrets/alert_manager_config --storage.path=/alertmanager
    volumes:
      - type: bind
        source: /root/devops/alert_manager_config.yml
        target: /alert_manager_config.yml
    deploy:
      placement:
        constraints:
          - node.labels.node == swarm-1
        
secrets: 
  alert_manager_config:
    external: true

networks:
  monitor:
    external: true