version: "3.4"
services:
  main:
    image: prom/alertmanager
    ports: 
      - 9093:9093
    networks:
      - monitor
    volumes:
      - type: bind
        source: /root/devops/alert_manager_config.yml
        target: /alert_manager_config.yml
    command: -storage.path=/alertmanager
    deploy:
      placement:
        constraints:
          - node.labels.node == swarm-1
        

networks:
  monitor:
    external: true