version: "3"
services:
  main:
    image: prom/alertmanager
    ports: 
      - 9093:9093
    networks:
      - monitor
    # volumes:
    #   - /root/devops/alert_manager_config.yml:/alert_manager_config.yml
    # command: -config.file=/alert_manager_config.yml -storage.path=/alertmanager
    deploy:
      placement:
        constraints:
          - node.labels.node == swarm-1
        

networks:
  monitor:
    external: true