version: "3"
services:
  alert-manager:
    image: prom/alertmanager
    ports: 
      - 9093:9093
    networks:
      - monitor
    volumes:
      - /root/devops/alert_manager_config.yml:/alert_manager_config.yml
    command: -config.file=/alert_manager_config.yml -storage.path=/alertmanager

networks:
  monitor:
    external: true