version: '3.2'
services:
  main:
    image: localhost:5000/go-demo:2
    environment:
      - DB=db
    networks:
      - go-demo
      - network1

    deploy:
      replicas: 3
      placement:
        constraints:
          - node.labels.env == worker
      labels:
        - com.df.notify=true
        - dom.df.distribute=true
        - com.df.serviceDomain=go-demo.com
        - com.df.servicePath=/demo
        - com.df.port=8080
      resouces:
        limits:
          memory: 10M
        reservations:
          memory: 5M
  db:
    image: mongo
    deploy:
      placement:
        constraints:
          - node.labels.env == worker
      resouces:
        limits: 
          memory: 10M
        reservations:
          memory: 5M
    networks:
      - go-demo

networks:
  network1:
    external: true
  go-demo:
    external: true
