version: "3.4"
services:
  monitor:
    image: vfarcic/docker-flow-monitor
    environment:
      - GLOBAL_SCRAPE_INTERVAL=10s
      - ARG_WEB_ROUTE-PREFIX=/monitor
    networks:
      - network1
      - monitor
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        = com.df.servicePath=/monitor
        - com.df.port=9090
  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - monitor
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/remove
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  monitor:
   external: true
  network1:
    external: true
        