version: "3.4"
services:
  monitor:
    image: vfarcic/docker-flow-monitor
    environment:
      - GLOBAL_SCRAPE_INTERVAL=10s
      - ARG_WEB_ROUTE-PREFIX=/monitor
      - ARG_WEB_EXTERNAL-URl=http://68.183.176.157/monitor
      - ARG_ALERTMANAGER_URL=http://alert-manager:9093
    networks:
      - network1
      - monitor
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/monitor
        - com.df.port=9090
  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - monitor
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://monitor:8080/v1/docker-flow-monitor/remove
    deploy:
      placement:
        constraints:
          - node.role == manager
  alert-manager:
    image: prom/alertmanager
    networks:
      - monitor
    volumes:
      - type: bind
        source: /root/devops/alert_manager_config.yml
        target: /alert_manager_config.yml
    command: --config.file=/alert_manager_config.yml --storage.path=/alertmanager
networks:
  monitor:
   external: true
  network1:
    external: true
        